AWSTemplateFormatVersion: 2010-09-09
Description: Create a role for us to assume
Parameters:
  BucketName:
    Type: String
    Default: "leotti"
Resources:
  StsRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: s3access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: 
                  - arn:aws:s3:::leotti
                  - arn:aws:s3:::leotti/*

