#!/usr/bin/env bash

echo "== creating bucket"

if [ -z "$1" ]; then
    echo "There needs to be a bucket name"
    exit 1
fi

aws s3api create-bucket \
 --bucket $1 \
 --query Location \
 --output text