#!/usr/bin/env bash
echo "== delete objects"
#exit immediatly if any command returns a non zero status
set -e

#check bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name"
    exit 1
fi

BUCKET_NAME=$1



aws s3 rm s3://leotti --recursive