#!/usr/bin/env bash
echo "== put object"


#check bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name"
    exit 1
fi

#check for filename prefix
if [ -z "$2" ]; then
    echo "There needs to be a filename"
    exit 1
fi

BUCKET_NAME=$1
FILENAME=$2

OBJECT_KEY=$(basename "$FILENAME")

aws s3api put-object \
 --bucket $BUCKET_NAME \
 --body $FILENAME \
 --key $OBJECT_KEY

